### ISSUE TITLE
Service failed to build

### ISSUE THREAD

**Issue by sebastianBreuer** [maxtacu/kali-linux-docker#1] opened 2019-04-01 10:33 UTC
After executing docker-compose build ( which is just building the Dockerfile and mapping the ports ) it will give me the mentioned error.

## Expected Behavior

The script should be able to install. 

## Current Behavior

The script aborts. 
```sh
...
The following packages will be REMOVED:
  libargon2-0 libdns-export1100 libdns-export1102 libisc-export169
0 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
After this operation, 5496 kB disk space will be freed.
Do you want to continue? [Y/n] Abort.
ERROR: Service 'kali' failed to build: The command '/bin/sh -c apt-get install -y --no-install-recommends --allow-unauthenticated         openssh-server pwgen sudo vim-tiny        supervisor         net-tools         lxde x11vnc xvfb autocutsel        xfonts-base lwm xterm         nginx         python-pip python-dev build-essential         mesa-utils libgl1-mesa-dri         dbus-x11 x11-utils     && apt-get autoclean     && apt-get autoremove     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

## Steps to Reproduce

1. Prepare a docker-compose file:
```yml 
kali:
  build: .
  ports:
  - "6080:80
```
2. Run the following command: 
```sh
cd /path/to/kali-linux-docker && docker-compose build
```

**Comment by tmxak** [comment] 2019-04-02 13:39
What version of compose do you have? 
Have you tried to build without compose (a simple `docker build .` in the project folder)?

**Comment by maxtacu** [comment] 2019-04-02 14:54
The issue is fixed. Please update your code. Thanks for your contribution. 
Closing the issue

**Closed as completed by maxtacu** 2019-04-02 14:54 UTC
